general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd =
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# OSD warning before dimming
listener {
    timeout = 120
    on-timeout = hyprctl notify 1 2000 "rgb(fab387)" " Dimming soon"
}

# Dim screen after 2.5 min idle
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# OSD warning before lock
listener {
    timeout = 270
    on-timeout = hyprctl notify 2 3000 "rgb(89b4fa)" " Locking soon"
}

# Lock after 5 min idle
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn off screens after 5.5 min idle
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# Suspend after 30 min idle
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
