exec-once = nm-applet --indicator

exec-once = mako
exec-once = hyprpaper
exec-once = hyprexpose
exec-once = ~/.config/hypr/wallpaper-auto.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = solaar -w hide
exec-once = ~/.local/bin/g915-rgb-daemon
exec-once = sleep 3 && solaar config 1 onboard_profiles Disabled && solaar config 1 rgb_control Solaar && solaar config 1 rgb_zone_1 "!LEDEffectSetting {ID: 1, color: 11501035}" && solaar config 1 rgb_zone_2 "!LEDEffectSetting {ID: 1, color: 11501035}" && solaar config 2 onboard_profiles Disabled && solaar config 2 rgb_control Solaar && solaar config 2 rgb_zone_1 "!LEDEffectSetting {ID: 1, color: 11501035}"
