env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GSK_RENDERER,vulkan
env = WLR_RENDERER,vulkan
env = GBM_BACKEND,nvidia-drm
env = GTK_THEME,Catppuccin-blue
env = QT_QPA_PLATFORMTHEME,qt5ct
env = XCURSOR_THEME,Catppuccin-blue
env = ELECTRON_FORCE_DARK_MODE,1
env = COLORFGBG,15;0
env = XCURSOR_SIZE,24
env = GDK_SCALE,1
