# DP-1 (izq): Samsung Odyssey G5 — secundario, workspaces 7-10
monitor = DP-1, 2560x1440@164.84, 0x0, 1
# DP-2 (der): MSI MAG 275CQ — principal, workspaces 1-6
monitor = DP-2, 2560x1440@165, 2560x0, 1

workspace = DP-2, 1
workspace = DP-2, 2
workspace = DP-2, 3
workspace = DP-2, 4
workspace = DP-2, 5
workspace = DP-2, 6
workspace = DP-1, 7
workspace = DP-1, 8
workspace = DP-1, 9
workspace = DP-1, 10
